# Generated by Django 3.2 on 2024-10-01 09:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('brandID', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('brandName', models.CharField(max_length=255)),
                ('brandLogo', models.ImageField(upload_to='brand_logos/')),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplierName', models.CharField(max_length=255)),
                ('supplierMobileNumber', models.CharField(max_length=255)),
                ('customerName', models.CharField(max_length=255)),
                ('customerMobileNumber', models.CharField(max_length=15)),
                ('invoiceDate', models.DateField(auto_now_add=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='UserRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile_number', models.CharField(max_length=15, unique=True)),
                ('alternate_number', models.CharField(blank=True, max_length=15, null=True)),
                ('address', models.TextField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verification', models.CharField(choices=[('aadharNumber', 'Aadhar Number'), ('panNumber', 'PAN Number'), ('voterId', 'Voter ID'), ('supplier', 'Supplier')], max_length=20)),
                ('shopName', models.CharField(blank=True, max_length=255, null=True)),
                ('shopPhoto', models.ImageField(blank=True, null=True, upload_to='shop_photos/')),
                ('email', models.EmailField(max_length=254)),
                ('user_registration', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='MilkProductapp.userregistration')),
            ],
        ),
        migrations.CreateModel(
            name='SupplierCustomerRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier_mobile_number', models.CharField(max_length=15)),
                ('customer_mobile_number', models.CharField(max_length=15)),
                ('supplier_name', models.CharField(max_length=255)),
                ('customer_name', models.CharField(max_length=255)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'unique_together': {('supplier_mobile_number', 'customer_mobile_number')},
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('productid', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('productCategory', models.CharField(max_length=255)),
                ('productType', models.CharField(max_length=255)),
                ('productImage', models.ImageField(blank=True, null=True, upload_to='product_images/')),
                ('productVolume', models.CharField(max_length=255)),
                ('productPrice', models.DecimalField(decimal_places=2, max_digits=10)),
                ('productDescription', models.TextField()),
                ('brandID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MilkProductapp.brand')),
            ],
        ),
        migrations.CreateModel(
            name='NegotiablePrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('final_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MilkProductapp.brand')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MilkProductapp.product')),
                ('relationship', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='negotiable_prices', to='MilkProductapp.suppliercustomerrelation')),
            ],
        ),
        migrations.CreateModel(
            name='InvoiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('volume', models.FloatField()),
                ('totalPrice', models.DecimalField(decimal_places=2, max_digits=10)),
                ('paymentMode', models.CharField(max_length=50)),
                ('paymentStatus', models.CharField(max_length=50)),
                ('transactionId', models.CharField(max_length=255)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MilkProductapp.invoice')),
                ('productItem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MilkProductapp.product')),
            ],
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MilkProductapp.cart')),
                ('productItem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MilkProductapp.product')),
            ],
        ),
        migrations.AddField(
            model_name='cart',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='MilkProductapp.userregistration'),
        ),
    ]
